<?xml version="1.0" encoding="UTF-8" ?>
		<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
		<channel>
			<title>Paranatural</title>
			<atom:link href="http://www.paranatural.net/rss.php" rel="self" type="application/rss+xml" />
			<link>http://www.paranatural.net/</link>
			<description>Latest Paranatural comics and news</description>
			<language>en-us</language><item><title><![CDATA[Paranatural - Chapter 5 Page 173]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-173"><img src="http://www.paranatural.net/comicsthumbs/1484882274-Ch5Pg173.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>Thanks for reading! I'll be here next week and I'll see you then!</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-173</link><author>tech@thehiveworks.com</author><pubDate>Thu, 19 Jan 2017 22:08:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-173</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 172]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-172"><img src="http://www.paranatural.net/comicsthumbs/1484634723-Ch5Pg172.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>Thanks for reading!</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-172</link><author>tech@thehiveworks.com</author><pubDate>Tue, 17 Jan 2017 01:24:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-172</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 171]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-171"><img src="http://www.paranatural.net/comicsthumbs/1484295832-Ch5Pg171.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>A NEW FRIEND</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-171</link><author>tech@thehiveworks.com</author><pubDate>Fri, 13 Jan 2017 03:21:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-171</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 170]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-170"><img src="http://www.paranatural.net/comicsthumbs/1484029999-Ch5Pg170.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>Thanks for reading my web-page</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-170</link><author>tech@thehiveworks.com</author><pubDate>Tue, 10 Jan 2017 01:32:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-170</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 169]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-169"><img src="http://www.paranatural.net/comicsthumbs/1483689899-Ch5Pg169.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>I'm cutting away to a different scene next time! See you then!</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-169</link><author>tech@thehiveworks.com</author><pubDate>Fri, 06 Jan 2017 02:59:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-169</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 168]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-168"><img src="http://www.paranatural.net/comicsthumbs/1483428159-Ch5Pg168.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>Thanks for reading!</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-168</link><author>tech@thehiveworks.com</author><pubDate>Tue, 03 Jan 2017 02:20:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-168</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 167]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-167"><img src="http://www.paranatural.net/comicsthumbs/1483121477-Ch5Pg167.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>I'm back to it! Easing back into work. Thank you for your continued readership while I recover and figure things out.</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-167</link><author>tech@thehiveworks.com</author><pubDate>Fri, 30 Dec 2016 13:08:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-167</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 166]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-166"><img src="http://www.paranatural.net/comicsthumbs/1481623015-Ch5Pg166.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p><strong>*EDIT* Hey guys! I tired my wrist out doing some other work and need to let it recover, so I don't have an update ready for today. Sorry about that! I'm resting up and will get back to it as soon as I can. Thanks for your understanding!</strong></p>
<p>&nbsp;</p>
<p>Thanks for reading!</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-166</link><author>tech@thehiveworks.com</author><pubDate>Tue, 13 Dec 2016 08:00:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-166</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 165]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-165"><img src="http://www.paranatural.net/comicsthumbs/1481280929-Ch5Pg165.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>Aaand we're back! Medicine cut my strep throat off in the cradle so I'm feeling right as rain. Thanks for the well wishes! See you next time!</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-165</link><author>tech@thehiveworks.com</author><pubDate>Fri, 09 Dec 2016 08:00:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-165</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 164]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-164"><img src="http://www.paranatural.net/comicsthumbs/1480716844-Ch5Pg164.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>Sorry for the wait, thanks for reading!</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-164</link><author>tech@thehiveworks.com</author><pubDate>Fri, 02 Dec 2016 17:12:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-164</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 163]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-163"><img src="http://www.paranatural.net/comicsthumbs/1479496075-Ch5Pg163.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>AAAAAND SCENE. We'll get back to these kids later. See you next time!</p>
<p>(P.S. I hope you all had a good holiday!)</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-163</link><author>tech@thehiveworks.com</author><pubDate>Tue, 29 Nov 2016 00:00:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-163</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 162]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-162"><img src="http://www.paranatural.net/comicsthumbs/1479495814-Ch5Pg162.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>Heads up, <strong>there won't be an update this Friday (I'm visiting family and taking time off for Thanksgiving)! The next page will go up on Tuesday the 29th! </strong>See you then and thanks for reading!</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-162</link><author>tech@thehiveworks.com</author><pubDate>Tue, 22 Nov 2016 00:00:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-162</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 161]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-161"><img src="http://www.paranatural.net/comicsthumbs/1479448747-Ch5Pg161.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>if you turn the other cheek fast enough you can really get some force behind it and use it for offensive striking purposes</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-161</link><author>tech@thehiveworks.com</author><pubDate>Fri, 18 Nov 2016 00:47:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-161</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 160]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-160"><img src="http://www.paranatural.net/comicsthumbs/1479183107-Ch5Pg160.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>Hey guys! I'm coming down with strep throat at the moment, so I'm iffy on if the next page will be on time. Right now I'm planning on doing it, so check back for updates! Thanks for reading!</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-160</link><author>tech@thehiveworks.com</author><pubDate>Mon, 14 Nov 2016 23:08:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-160</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 159]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-159"><img src="http://www.paranatural.net/comicsthumbs/1478843125-Ch5Pg159.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>We're going to another scene next time, one I'm very excited for! There's a lot to look forward to coming up in this chapter and onward, so I hope you will keep checking back. I'll be doing my best to make Paranatural a bright little moment in your week. Thank you very, very much for reading and for sharing your time with me! &lt;3</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-159</link><author>tech@thehiveworks.com</author><pubDate>Fri, 11 Nov 2016 00:25:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-159</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 158]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-158"><img src="http://www.paranatural.net/comicsthumbs/1478580260-Ch5Pg158.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>Thanks for reading! :O</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-158</link><author>tech@thehiveworks.com</author><pubDate>Mon, 07 Nov 2016 23:42:00 -0500</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-158</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 157]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-157"><img src="http://www.paranatural.net/comicsthumbs/1478234641-Ch5Pg157.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>We're back! Thanks for reading!</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-157</link><author>tech@thehiveworks.com</author><pubDate>Fri, 04 Nov 2016 00:41:00 -0400</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-157</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 156]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-156"><img src="http://www.paranatural.net/comicsthumbs/1477618510-Ch5Pg156.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>I'm gonna be very busy this weekend, so the next update will be art instead of a page. See you Monday, thanks for reading!</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-156</link><author>tech@thehiveworks.com</author><pubDate>Thu, 27 Oct 2016 21:31:00 -0400</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-156</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 155]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-155"><img src="http://www.paranatural.net/comicsthumbs/1477362167-Ch5Pg155.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>We're back to http://www.paranatural.net//comic/chapter-5-page-126"&gt;Max. Thanks for reading!</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-155</link><author>tech@thehiveworks.com</author><pubDate>Mon, 24 Oct 2016 22:20:00 -0400</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-155</guid></item><item><title><![CDATA[Paranatural - Chapter 5 Page 154]]></title><description><![CDATA[<a href="http://www.paranatural.net/comic/chapter-5-page-154"><img src="http://www.paranatural.net/comicsthumbs/1477083289-Ch5Pg154.png" /><br />New comic!</a><br />Today's News:<br /><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<p>Featuring a first panel cameo from my friend <a href="https://twitter.com/burgeroise">Ivy</a>'s characters from the comic she's making, <a href="https://www.patreon.com/Burgeroise">Coquette Dragoon</a>! Thanks for your patience and for reading! See you next time.</p>
]]></description><link>http://www.paranatural.net/comic/chapter-5-page-154</link><author>tech@thehiveworks.com</author><pubDate>Fri, 21 Oct 2016 16:51:00 -0400</pubDate><guid>http://www.paranatural.net/comic/chapter-5-page-154</guid></item></channel></rss>